server:
    port: 8181
management:
  endpoints:
          web:
            exposure:
                include: refresh # Exposing the Actuator end point to refresh if any value changed
spring:
  profiles:
    active: dev # profile name which is being used to fetch the details